### ISSUE TITLE
windows下报错 

### ISSUE THREAD

**Issue by mlyknown** [V-Tom/vue-blog#1]
ERROR in ./src/t-tom.me/static/index.js
Module build failed: ReferenceError: Unknown plugin "transform-es2015-classes" specified in "E:\MyProject\bishe\vue-blog\.babelrc" at 0, attempted to resolve relative to "E:\MyProject\bishe\vue-blog"
    at E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\options\option-manager.js:179:17
    at Array.map (native)
    at Function.normalisePlugins (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\options\option-manager.js:155:20)
    at OptionManager.mergeOptions (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\options\option-manager.js:277:36)
    at OptionManager.addConfig (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\options\option-manager.js:207:10)
    at OptionManager.findConfigs (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\options\option-manager.js:413:16)
    at OptionManager.init (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\options\option-manager.js:461:12)
    at File.initOptions (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\index.js:194:75)
    at new File (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\file\index.js:123:22)
    at Pipeline.transform (E:\MyProject\bishe\vue-blog\node_modules\babel-core\lib\transformation\pipeline.js:45:16)
 @ multi main

**Comment by V-Tom** [comment]
请确定 `npm install -d` 把所有的包正确安装。

`babel-plugin-transform-es2015-classes`在`node_modules`可以找到

如果网络不好，可以换cnpm或者切换到vpn下。
